### ISSUE TITLE
Not being able to decrease screen shaking in mobile

### ISSUE THREAD

**Issue by KUsussy** [vret001/KU#317]
**Describe the bug**

**When did you last experience the issue:**
April 26 2022

**To Reproduce**
1. Go to settings
2. Look for camera shake
3. Use the slider or number
4. It goes back to 50

**Expected behavior**
every single time

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPad 
 - OS:
 - 
 - Version [e.g. 2 Shaking lags the game, makes it difficult to play. Please fix this

**Comment by VixenSaid** [comment]
To add onto this. The sliders on mobile have been broken ever since the settings have gotten a rework. I have no other option but mobile. I noticed that the screen shake for g19 is extremely bad and hard to play with, but being unable to adjust it makes it even harder. Please test this yourself if you have the chance. All you have to do is turn the slider down to zero, spawn in, attack a couple times, and then respawn to see the slider reset and is not working. I also tried the fix by typing in the number which also does not work. The number resets back to 50 regardless. https://user-images.githubusercontent.com/63977689/165412080-c0aa40d8-7145-40c6-b60f-bb8d6efc874e.MOV

https://user-images.githubusercontent.com/63977689/165412249-894c8e2a-dddc-4430-8ef7-571f9c08b822.MOV

**Comment by Mechagator05** [comment]
To make sure the devs know and fix it on there too. This is also happening on Xbox
