### ISSUE TITLE
Millenium & Type-2 Kiryu Glitch

### ISSUE THREAD

**Issue by pegente** [vret001/KU#682]
@WakatÆ discovered this flaw. I have all the requirements for Type-2, including Millennium Gojira, but I can't buy it. It says I don't have a Level 30 Millennium Gojira, but I do. My Roblox username: pegente34 I have all the Gcells and I have level 50 Gojira 1954 This is in Kaiju Universe by the way.
![Screenshot_20220928_155556](https://user-images.githubusercontent.com/114621095/192889113-ddce108c-3516-4ac2-8f76-b1e95fc7f45c.jpg)

**Comment by blackninjasorcerorv2** [comment]
Me to I have all the requirements including millennium Godzilla which is level 31 but it  says I don’t have it level 30 but I do

**Comment by ItzShadowyPlayz** [comment]
same i have level 41 millennium already :(

**Comment by Kingo253** [comment]
i know whats wrong

**Comment by Kingo253** [comment]
So, when I got my goji to level 50 and mil to level 30 the kir requirements said I didn't have a level 30 mil I tried rejoining and no luck pls fix this.

To reproduce: Go to kaiju selection in menu
go to the requirements for kir and if you just got mill to level 30 it says it isn't level 30 because of the spelling error of the Millenium Godzilla. The Millenium rework has 2 n's but the requirement Millenium for kir has 1 n

**Comment by blackninjasorcerorv2** [comment]
I see hope they fix this

**Comment by supremeshiva99** [comment]
ye

**Comment by pegente** [comment]
¡THANK!
